server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/housie
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        diaclet: org.hibernate.diaclet.MySQL5Dialect
        format_sql: true
    show-sql: true
  devtools:
    restart:
      enabled: true