server:
  port: 9296    #application port

spring:
  application:
    name: CONFIG-SERVER #application name
  profiles:
    active: native


logging:
  file:
    name: d:/logs/application-debug.log
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"