spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296 #to fetch properties from config server
  cloud:
    gateway:
      routes:
        - id: ADMIN-PORTAL
          uri: http://localhost:8082
          predicates:
            - Path=/event/**, /prizeconfigure/**, /prizemaster/**
        - id: WEB-PORTAL
          uri: http://localhost:8083
          predicates:
            - Path=/login.html
server:
  port: 8080


zipkin:
  base-url: http://127.0.0.1:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'


  cloud:
    config:
      enabled: true
      uri: http://localhost:9296