server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/housie
  application:
    name: api-gateway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "optional:configserver:http://localhost:9296"
  cloud:
    gateway:
      routes:
        - id: admin-portal
          uri: lb://admin-portal
          predicates:
            - Path=/event/**, /prizeconfigure/**, /prizemaster/**, /home, /admin/**, /user/**
          filters:
            - name: CircuitBreaker
              args:
                name: admin-portal
                fallbackuri: forward:/adminServiceFallBack
        - id: web-portal
          uri: lb://web-portal
          predicates:
            - Path=/login.html, /css/**, /js/**
          filters:
            - name: CircuitBreaker
              args:
                name: web-portal
                fallbackuri: forward:/webServiceFallBack
        - id: securityapp
          uri: lb://securityapp
          predicates:
            - Path=/livelogin, /login


logging:
  file:
    name: d:/logs/application-debug1.log
  level:
    org:
      springframework: DEBUG
      hibernate:
        sql: DEBUG

