spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296 #to fetch properties from config server
  cloud:
    gateway:
      routes:
        - id: ADMIN-PORTAL
          uri: lb://ADMIN-PORTAL
          predicates:
            - Path=/event/**, /prizeconfigure/**, /prizemaster/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADMIN-PORTAL
                fallbackuri: forward:/adminServiceFallBack
        - id: WEB-PORTAL
          uri: lb://WEB-PORTAL
          predicates:
            - Path=/login.html
          filters:
            - name: CircuitBreaker
              args:
                name: WEB-PORTAL
                fallbackuri: forward:/webServiceFallBack
      discovery:
        locator:
          enabled: true
    config:
      enabled: true
      uri: lb:http://localhost:9296
server:
  port: 8080

zipkin:
  base-url: http://127.0.0.1:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'


